const popularCities = [
    "Rome",
    "Paris",
    "Frankfurt",
    "Tokyo",
    "Delhi",
    "Shanghai",
    "São Paulo",
    "Mumbai",
    "Mexico City",
    "Beijing",
    "Osaka",
    "Cairo",
    "New York City",
    "Dhaka",
    "Karachi",
    "Buenos Aires",
    "Istanbul",
    "Kolkata",
    "Manila",
    "Lagos",
    "Rio de Janeiro",
    "Tianjin",
    "Kinshasa",
    "Guangzhou",
    "Los Angeles",
    "Moscow",
    "Shenzhen",
    "Lahore",
    "Bangalore",
    "Paris",
    "Bogotá",
    "Jakarta",
    "Chennai",
    "Milano",
    "Mucnhen",
    "Koeln",
    "Berlin",
];